### PR TITLE
Change the Way the Resulting Markdown Header is Created

### PR DESCRIPTION
**Pull request by fer-rum**
Hi,
So, I tinkered with the _pagemaster_ to make it work for a current project and thought that I might upstream the changes so you can take them over if you like them.

## Main Changes:
In addition to a _id_key_ now also a _title_key_ is required in the `_config.yml`
The _title_key_ gives the name of the field within a collection entry which will
be set as the pages' title via the Markdown frontmatter _title_.
The collection entry itself will no longer be pasted 1:1 into the Markdown
frontmatter but rather be a subobject of the _data_ field.

### Example
_config.yml
``` yml
collections:
  members:
    output:     true
    source:     team.yml
    id_key:     id
    title_key:  name
    layout:     member
```
together with  _data/team.yml
``` yml
- id:           yml-test
  name:         Einstein, Albert
  title:        Prof. Dr.
```
yields _members/yml-test.md
```markdown
---
layout: member
title: Einstein, Albert
data:
  id: yml-test
  name: Einstein, Albert
  title: Prof. Dr.
---
```

## Minor Changes:
	* Refactored some modifiers into statements for better reading flow.
	* Added parentheses for easier discerning of method application
	* Renamed iterators to be more meaningful
	* Renamed "overwrite_pages" to "remove_output_dir" to better match
	  its actual function
	* Added documentation comments

### CODE REVIEW

**Comment by fer-rum** [comment]
After https://github.com/mnyrop/pagemaster/pull/21/commits/ecc72238ef7a39f514a4e7fdd122e69b99e1ef97 I realized that there basically are three kinds of keys to consider:
1. **Direct** Keys that get copied directly into the generated Markdown, like e.g. the `layout` key.
2. **Indirect** Keys which name a key in the data of which the associated value gets copied into the Markdown, like the `title_key`
3. **Implicit** Keys that are generated into the Markdown. Their functionality is determined by whatever the pagemaster :tm: decides. An example would be the `data` key I introduced earlier.

Maybe this observation can help form an idea of how to better organize keys in future iterations.

**Comment by mnyrop** [comment]
hi @fer-rum, i'm working on a refactored version of pagemaster that allows jekyll 4.0, is more modular, and will be easier to semantically version more transparently wrt breaking changes.

your pr is making me think that another feature should be the ability to better control + customize your pagemaster configuration. i think this could follow a rails model where there are 'sensible defaults' (e.g., the current options of required `id_key`, `layout`, non-required keys as available), but also the ability to reconfigure these in a meta way (i.e., customize which keys are essential, which are direct/indirect, etc.)

is it ok if i cherry-pick some of your commits/ideas here and then @ you after? if so, i'll close this pr but link it to a new issue.

**Comment by fer-rum** [comment]
Sure go ahead. I am quite a ruby-newbie (This is in fact the first ruby code I ever touched) so you probably can do a lot better then me.
Do you have a rough schedule when you will release a new version?
Cheers.

**Comment by fer-rum** [comment]
Oh, by-the-by, if you can think of a clever way to specify additional markdown blobs that can be copied into the body of the generated markdown, I would be interested. I found my `_data/team.yml` getting cluttered with all kinds of lengthy pieces of text (like CVs, paper references, job descriptions… some people really tend to write a novel about themselves).

**Comment by mnyrop** [comment]
2 things I'd like to do that might help you there:

1. Enable a `content` field that populates the page body/content, which will work if you don't need to control the blobs granularly and you don't mind a having a really large csv/json file.

2. Write this plugin in reverse (I might call it `jekyll vacuum` or something), which would take existing markdown pages with content, and convert them to JSON objects with the YAML front matter and content as fields. This would probably include an option/flag for capturing content in plaintext (with HTML tags and liquid removed).

e.g., 

```yaml
---
pid: 0001
title: my title
arbitrary_list:
  - a
  - b
  - c
---
Pretend this is a lot of prose with <b>some html tags</b> and {% raw %} liquid blocks {% endraw %} embedded as well as some "quotations." Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet pellentesque eleifend. Donec suscipit pulvinar lobortis. Vestibulum iaculis et sem eu ultrices. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam eu dolor dui. Phasellus nisi odio, semper non odio quis, venenatis pellentesque elit. Cras egestas rutrum venenatis. Aliquam a velit sed lacus mattis viverra. Integer tempus consectetur neque eget mollis. Sed laoreet ante in lectus ultrices mattis at quis est.

Ut vitae risus eu felis porta bibendum et quis augue. Maecenas tempor, metus suscipit sollicitudin ornare, ligula lacus pulvinar tortor, condimentum commodo dui velit nec lectus. Curabitur porta tincidunt mauris, consequat sodales lacus vehicula sit amet. Vestibulum sit amet luctus diam. Phasellus eu mollis ante. Phasellus maximus aliquet tincidunt. Pellentesque hendrerit tortor at diam porttitor, et aliquam nisl mollis. Maecenas vitae blandit purus. Vivamus mi dolor, aliquet sed convallis sit amet, viverra ut magna. Sed scelerisque nisl ut malesuada varius. Maecenas egestas est ut laoreet viverra.
```

would become 

```json
{
  "pid": "0001",
  "title": "my title",
  "arbitrary_list": ["a", "b", "c"],
  "content": "Pretend this is a lot of prose with <b>some html tags</b> and {% raw %} liquid blocks {% endraw %} embedded as well as some \"quotations.\" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet pellentesque eleifend. Donec suscipit pulvinar lobortis. Vestibulum iaculis et sem eu ultrices. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam eu dolor dui. Phasellus nisi odio, semper non odio quis, venenatis pellentesque elit. Cras egestas rutrum venenatis. Aliquam a velit sed lacus mattis viverra. Integer tempus consectetur neque eget mollis. Sed laoreet ante in lectus ultrices mattis at quis est.\nUt vitae risus eu felis porta bibendum et quis augue. Maecenas tempor, metus suscipit sollicitudin ornare, ligula lacus pulvinar tortor, condimentum commodo dui velit nec lectus. Curabitur porta tincidunt mauris, consequat sodales lacus vehicula sit amet. Vestibulum sit amet luctus diam. Phasellus eu mollis ante. Phasellus maximus aliquet tincidunt. Pellentesque hendrerit tortor at diam porttitor, et aliquam nisl mollis. Maecenas vitae blandit purus. Vivamus mi dolor, aliquet sed convallis sit amet, viverra ut magna. Sed scelerisque nisl ut malesuada varius. Maecenas egestas est ut laoreet viverra."
}
```

Would this be useful? For the latter, I'm imagining your team writing their own `md` pages with you being able to store/manipulated them as JSON for other uses.

Because I work in humanities/academia, this functionality is important for folks adding long transcriptions or translations to items while still being able to regenerate pages from object metadata. While quite different in most ways, there might still be useful overlap for your use case?

Per your earlier comment, I'd like to get a new version out in the next month. Fingers crossed.
Also, thank you for your PR and for engaging this open source project so readily. It's really appreciated.

**Comment by fer-rum** [comment]
Thanks for the heads-up. Yes, I think the suggested changes can help with what I have in mind. The `jekyll vaccum` idea sound interesting as well and may enable us to experiment with new, more contributor-friendly workflows. I am looking forward to it.

**Comment by fer-rum** [comment]
@mnyrop Hi, me again. Can you give a quick heads-up on the current progress (Just for planning the projects that want to use a new version of _pagemaster_)?

**Pull request closed without merging**
